[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']

remappings = [
  'openzeppelin-contracts/=lib/openzeppelin-contracts/'
]

solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
