name: docker-offchain
on:
  push:
    tags: ['v*.*.*']
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./offchain
          push: true
          tags: ghcr.io/${{ github.repository }}/dvp-worker:${{ github.ref_name }}
